In [ ]:
import tensorflow as tf
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import joblib

In [ ]:
files = os.listdir(r'/content/drive/MyDrive/Data Cuaca/Stasiun Bandung/')
files.sort()
kolom = ['Tn','Tx','Tavg','RH_avg','RR','ss','ff_x','ddd_x','ff_avg']
df_bandung = pd.DataFrame(columns = kolom)

for file in files :
  a = pd.read_excel(r'/content/drive/MyDrive/Data Cuaca/Stasiun Bandung/' + file,na_values = [8888,9999,"NaN"],header=8)
  a.dropna(axis=0,inplace=True)
  df_bandung = df_bandung.append({'Tn':a.mean()[0],'Tx':a.mean()[1],'Tavg':a.mean()[2],'RH_avg':a.mean()[3],'RR':a.mean()[4],
                'ss':a.mean()[5],'ff_x':a.mean()[6],'ddd_x':a.mean()[7],'ff_avg':a.mean()[8]},ignore_index = True)

df_bandung = df_bandung.interpolate(method ='linear', limit_direction ='forward')  
ff_x = df_bandung.pop('ff_x')
ddd_x = df_bandung.pop('ddd_x')

wd_rad = ddd_x*np.pi / 180

df_bandung['ff_x'] = ff_x*np.cos(wd_rad)
df_bandung['ff_y'] = ff_x*np.sin(wd_rad)

df_bandung

           Tn         Tx       Tavg  ...    ff_avg          ff_x          ff_y
0   20.791667  27.620833  23.312500  ...  2.416667  2.943141e-01 -4.490365e+00
1   19.750000  28.960714  23.646429  ...  1.821429 -2.611570e-01 -3.096148e+00
2   18.259259  30.370370  23.407407  ...  1.814815 -3.220859e+00  9.371743e-02
3   20.916667  27.808333  23.154167  ...  2.208333 -7.347881e-16 -4.000000e+00
4   19.321429  29.042857  23.146429  ...  1.678571 -2.870328e+00 -7.404088e-01
5   19.000000  30.808333  23.891667  ...  1.750000 -3.070184e+00  9.313300e-01
6   20.935484  28.306452  23.429032  ...  2.161290 -2.078276e+00 -3.530485e+00
7   20.392857  28.678571  23.507143  ...  1.535714 -2.540173e+00  1.596096e+00
8   19.130435  30.065217  23.782609  ...  1.695652 -3.024563e+00  3.387942e-01
9   20.285714  27.014286  23.371429  ...  1.571429  1.246411e-01  3.569253e+00
10  19.888889  29.366667  25.033333  ...  0.666667 -1.800567e+00 -2.259123e+00
11  18.750000  29.200000  23.450000  ...  1.000000  6.262790e-01 -4.456206e+00
12  20.363636  28.618182  23.263636  ...  1.090909 -1.490289e+00 -4.197858e+00
13  19.687500  29.768750  23.568750  ...  1.250000 -3.486258e+00 -7.330813e-01
14  18.750000  31.487500  23.750000  ...  1.625000 -2.772082e+00 -2.136718e+00
15  20.823529  29.317647  23.658824  ...  1.411765 -3.070011e+00 -1.857542e+00
16  21.055556  29.105556  23.861111  ...  1.111111 -2.997744e+00 -1.163261e-01
17  20.458333  29.016667  23.641667  ...  1.625000 -3.440179e+00 -1.002721e+00
18  21.136364  29.440909  24.277273  ...  2.636364 -1.597804e+00 -4.737829e+00
19  20.347826  29.760870  24.117391  ...  1.826087 -3.274030e+00  2.518178e+00
20  19.480000  30.536000  24.012000  ...  1.560000 -2.978035e+00  2.360362e+00
21  20.653846  28.123077  23.411538  ...  2.576923 -2.130990e+00 -4.734865e+00
22  19.758621  29.934483  23.793103  ...  1.413793 -3.482759e+00  4.265149e-16
23  18.925926  30.981481  23.822222  ...  2.185185 -4.223353e+00  1.384334e+00
24  20.551613  28.961290  23.680645  ...  2.322581 -8.546894e-01 -5.188135e+00
25  20.055172  29.713793  23.851724  ...  1.620690 -4.269429e+00 -8.059186e-01
26  18.241379  31.889655  23.800000  ...  2.241379 -4.774341e+00  1.233196e+00
27  21.200000  28.953846  23.865385  ...  2.000000 -1.326883e+00 -4.580933e+00
28  20.614286  29.366667  23.904762  ...  1.333333 -3.093364e+00 -1.585875e+00
29  19.883333  30.583333  24.258333  ...  2.000000 -2.335413e+00  3.550823e+00

[30 rows x 9 columns]

In [ ]:
files = os.listdir(r'/content/drive/MyDrive/Data Cuaca/Stasiun Bogor/')
files.sort()
kolom = ['Tn','Tx','Tavg','RH_avg','RR','ss','ff_x','ddd_x','ff_avg']
df_bogor = pd.DataFrame(columns = kolom)

for file in files :
  a = pd.read_excel(r'/content/drive/MyDrive/Data Cuaca/Stasiun Bogor/' + file,na_values = [8888,9999,"NaN"],header=8)
  a.dropna(axis=0,inplace=True)
  df_bogor = df_bogor.append({'Tn':a.mean()[0],'Tx':a.mean()[1],'Tavg':a.mean()[2],'RH_avg':a.mean()[3],'RR':a.mean()[4],
                'ss':a.mean()[5],'ff_x':a.mean()[6],'ddd_x':a.mean()[7],'ff_avg':a.mean()[8]},ignore_index = True)

df_bogor = df_bogor.interpolate(method ='linear', limit_direction ='forward')  
ff_x = df_bogor.pop('ff_x')
ddd_x = df_bogor.pop('ddd_x')

wd_rad = ddd_x*np.pi / 180

df_bogor['ff_x'] = ff_x*np.cos(wd_rad)
df_bogor['ff_y'] = ff_x*np.sin(wd_rad)

df_bogor

           Tn         Tx       Tavg  ...    ff_avg      ff_x      ff_y
0   22.740741  29.733333  25.481481  ...  1.037037  1.701676 -3.944928
1   22.966667  31.940000  26.056667  ...  0.500000 -0.731462 -3.046759
2   21.814815  33.114815  26.003704  ...  1.111111  3.477147 -1.040990
3   22.888889  29.629630  25.085185  ...  1.333333  0.630279 -3.574487
4   22.666667  32.314815  26.055556  ...  1.111111  2.021508 -2.556614
5   21.517241  33.668966  25.979310  ...  2.448276  3.777776 -2.002850
6   22.925926  29.600000  25.285185  ...  1.888889  0.245500 -4.215079
7   23.115385  32.042308  26.196154  ...  1.769231 -0.714087 -3.896648
8   22.691026  30.179487  25.403077  ...  1.251282  0.003874 -3.847434
9   22.266667  28.316667  24.610000  ...  0.733333  0.680346 -3.670818
10  23.066667  32.216667  26.256667  ...  2.200000 -0.513188 -4.504192
11  21.366667  33.376667  26.286667  ...  2.666667 -3.368923 -3.033392
12  22.923077  29.361538  24.961538  ...  1.923077 -1.305340 -5.619618
13  22.636364  32.172727  26.154545  ...  1.454545 -2.909537 -3.252063
14  21.800000  33.680000  26.260000  ...  2.600000 -4.458869  4.014784
15  23.478261  31.930435  26.239130  ...  2.000000 -4.567657  3.329201
16  24.125000  32.681250  27.125000  ...  1.687500  1.055143 -4.759443
17  23.142857  31.766667  26.157143  ...  1.857143  5.777761 -1.218067
18  22.888889  30.050000  25.627778  ...  1.722222  5.445061 -4.659660
19  23.388889  31.872222  26.233333  ...  1.388889  3.934610 -3.433723
20  22.500000  32.975000  26.550000  ...  1.250000  5.125554 -1.136308
21  23.105263  29.542105  25.415789  ...  2.421053  2.114377 -7.223215
22  22.818182  32.272727  26.300000  ...  1.636364  4.043503 -2.783748
23  22.545455  33.309091  26.118182  ...  2.000000  4.878095 -4.364306
24  23.206667  30.646667  25.720000  ...  1.133333  1.462727 -3.434852
25  23.040000  32.540000  26.810000  ...  1.000000 -3.814868 -1.202823
26  21.142857  32.571429  25.971429  ...  1.000000 -1.487601 -3.089036
27  23.077778  29.800000  25.727778  ...  1.333333  0.579727 -3.957767
28  23.527273  32.100000  26.681818  ...  1.545455 -3.273099 -2.746456
29  22.400000  33.045455  26.700000  ...  1.636364 -3.550565 -2.838070

[30 rows x 9 columns]

In [ ]:
column_indices_bandung = {name: i for i, name in enumerate(df_bandung.columns)}

n = len(df_bandung)
print(n)
train_df_bandung = df_bandung[0:int(n*0.8)]
val_df_bandung = df_bandung[int(n*0.8):]

num_features = df_bandung.shape[1]
val_df_bandung

30

           Tn         Tx       Tavg  ...    ff_avg      ff_x      ff_y
24  20.551613  28.961290  23.680645  ...  2.322581 -0.854689 -5.188135
25  20.055172  29.713793  23.851724  ...  1.620690 -4.269429 -0.805919
26  18.241379  31.889655  23.800000  ...  2.241379 -4.774341  1.233196
27  21.200000  28.953846  23.865385  ...  2.000000 -1.326883 -4.580933
28  20.614286  29.366667  23.904762  ...  1.333333 -3.093364 -1.585875
29  19.883333  30.583333  24.258333  ...  2.000000 -2.335413  3.550823

[6 rows x 9 columns]

In [ ]:
column_indices_bogor = {name: i for i, name in enumerate(df_bogor.columns)}

n = len(df_bogor)
print(n)
train_df_bogor = df_bogor[0:int(n*0.8)]
val_df_bogor = df_bogor[int(n*0.8):]

num_features = df_bogor.shape[1]
val_df_bogor

30

           Tn         Tx       Tavg  ...    ff_avg      ff_x      ff_y
24  23.206667  30.646667  25.720000  ...  1.133333  1.462727 -3.434852
25  23.040000  32.540000  26.810000  ...  1.000000 -3.814868 -1.202823
26  21.142857  32.571429  25.971429  ...  1.000000 -1.487601 -3.089036
27  23.077778  29.800000  25.727778  ...  1.333333  0.579727 -3.957767
28  23.527273  32.100000  26.681818  ...  1.545455 -3.273099 -2.746456
29  22.400000  33.045455  26.700000  ...  1.636364 -3.550565 -2.838070

[6 rows x 9 columns]

In [ ]:
class WindowGenerator():
  def __init__(self, input_width, label_width, shift,
               train_df, val_df,df,
               label_columns=None):
    self.train_df = train_df
    self.val_df = val_df
    self.df = df

    self.label_columns = label_columns
    if label_columns is not None:
      self.label_columns_indices = {name: i for i, name in
                                    enumerate(label_columns)}
    self.column_indices = {name: i for i, name in
                           enumerate(train_df.columns)}

    self.input_width = input_width
    self.label_width = label_width
    self.shift = shift

    self.total_window_size = input_width + shift

    self.input_slice = slice(0, input_width)
    self.input_indices = np.arange(self.total_window_size)[self.input_slice]

    self.label_start = self.total_window_size - self.label_width
    self.labels_slice = slice(self.label_start, None)
    self.label_indices = np.arange(self.total_window_size)[self.labels_slice]

  def __repr__(self):
    return '\n'.join([
        f'Total window size: {self.total_window_size}',
        f'Input indices: {self.input_indices}',
        f'Label indices: {self.label_indices}',
        f'Label column name(s): {self.label_columns}'])

In [ ]:
width = 4
bandung = WindowGenerator(input_width=width, label_width=1, shift=1,train_df =  train_df_bandung,val_df = val_df_bandung, df = df_bandung )
bogor =  WindowGenerator(input_width=width, label_width=1, shift=1,train_df =  train_df_bogor,val_df = val_df_bogor, df = df_bogor )

bandung
bogor

Total window size: 5
Input indices: [0 1 2 3]
Label indices: [4]
Label column name(s): None

In [ ]:
def split_window(self, features):
  inputs = features[:, self.input_slice, :]
  labels = features[:, self.labels_slice, :]
  if self.label_columns is not None:
    labels = tf.stack(
        [labels[:, :, self.column_indices[name]] for name in self.label_columns],
        axis=-1)

  inputs.set_shape([None, self.input_width, None])
  labels.set_shape([None, self.label_width, None])

  return inputs, labels

WindowGenerator.split_window = split_window

In [ ]:
def make_dataset(self, data):
  data = np.array(data, dtype=np.float32)
  ds = tf.keras.preprocessing.timeseries_dataset_from_array(
      data=data,
      targets=None,
      sequence_length=self.total_window_size,
      sequence_stride=1,
      shuffle=True,
      batch_size=2)

  ds = ds.map(self.split_window)

  return ds

WindowGenerator.make_dataset = make_dataset

In [ ]:
@property
def train(self):
  return self.make_dataset(self.train_df)

@property
def val(self):
  return self.make_dataset(self.val_df)

WindowGenerator.train = train
WindowGenerator.val = val

In [ ]:
model_bandung = tf.keras.Sequential([
    tf.keras.layers.Conv1D(filters=32,
                           kernel_size=(width,),
                           activation='relu'),
    tf.keras.layers.Dense(units=16, activation='relu'),
    tf.keras.layers.Dense(units=32, activation='relu'),
    tf.keras.layers.Dense(units=num_features),
])

In [ ]:
model_bogor = tf.keras.Sequential([
    tf.keras.layers.Conv1D(filters=32,
                           kernel_size=(width,),
                           activation='relu'),
    tf.keras.layers.Dense(units=16, activation='relu'),
    tf.keras.layers.Dense(units=32, activation='relu'),
    tf.keras.layers.Dense(units=num_features),
])

epochs = 20

In [ ]:
model_bandung.compile(loss=tf.losses.MeanSquaredError(),
                optimizer=tf.optimizers.Adam(0.001),
                metrics=[tf.metrics.MeanAbsoluteError()])

history_bandung = model_bandung.fit(bandung.train, epochs=epochs,
                      validation_data=bandung.val)

Epoch 1/20
10/10 [==============================] - 1s 28ms/step - loss: 804.1453 - mean_absolute_error: 19.3774 - val_loss: 761.2568 - val_mean_absolute_error: 19.3800
Epoch 2/20
10/10 [==============================] - 0s 7ms/step - loss: 708.5869 - mean_absolute_error: 18.4300 - val_loss: 679.0753 - val_mean_absolute_error: 18.4102
Epoch 3/20
10/10 [==============================] - 0s 8ms/step - loss: 619.4526 - mean_absolute_error: 17.1122 - val_loss: 579.2706 - val_mean_absolute_error: 16.6504
Epoch 4/20
10/10 [==============================] - 0s 8ms/step - loss: 511.7701 - mean_absolute_error: 15.0794 - val_loss: 458.7945 - val_mean_absolute_error: 14.2019
Epoch 5/20
10/10 [==============================] - 0s 8ms/step - loss: 387.1160 - mean_absolute_error: 12.9050 - val_loss: 326.4317 - val_mean_absolute_error: 12.8093
Epoch 6/20
10/10 [==============================] - 0s 8ms/step - loss: 258.0027 - mean_absolute_error: 11.3080 - val_loss: 190.2102 - val_mean_absolute_error: 10.0267
Epoch 7/20
10/10 [==============================] - 0s 7ms/step - loss: 129.4712 - mean_absolute_error: 7.8457 - val_loss: 72.7829 - val_mean_absolute_error: 6.1299
Epoch 8/20
10/10 [==============================] - 0s 7ms/step - loss: 41.2145 - mean_absolute_error: 4.3210 - val_loss: 13.6904 - val_mean_absolute_error: 2.7242
Epoch 9/20
10/10 [==============================] - 0s 8ms/step - loss: 9.1775 - mean_absolute_error: 2.1451 - val_loss: 14.0013 - val_mean_absolute_error: 2.4250
Epoch 10/20
10/10 [==============================] - 0s 7ms/step - loss: 11.1639 - mean_absolute_error: 2.2166 - val_loss: 13.6747 - val_mean_absolute_error: 2.4928
Epoch 11/20
10/10 [==============================] - 0s 7ms/step - loss: 8.4500 - mean_absolute_error: 1.9452 - val_loss: 10.6723 - val_mean_absolute_error: 2.1619
Epoch 12/20
10/10 [==============================] - 0s 7ms/step - loss: 7.6027 - mean_absolute_error: 1.7550 - val_loss: 10.3070 - val_mean_absolute_error: 2.1040
Epoch 13/20
10/10 [==============================] - 0s 9ms/step - loss: 8.0716 - mean_absolute_error: 1.8235 - val_loss: 10.4247 - val_mean_absolute_error: 2.1496
Epoch 14/20
10/10 [==============================] - 0s 7ms/step - loss: 7.9110 - mean_absolute_error: 1.7903 - val_loss: 10.2846 - val_mean_absolute_error: 2.0911
Epoch 15/20
10/10 [==============================] - 0s 7ms/step - loss: 7.9148 - mean_absolute_error: 1.7603 - val_loss: 9.9859 - val_mean_absolute_error: 2.0448
Epoch 16/20
10/10 [==============================] - 0s 8ms/step - loss: 7.9389 - mean_absolute_error: 1.7666 - val_loss: 10.6515 - val_mean_absolute_error: 2.1035
Epoch 17/20
10/10 [==============================] - 0s 8ms/step - loss: 7.4795 - mean_absolute_error: 1.7098 - val_loss: 9.9783 - val_mean_absolute_error: 2.0111
Epoch 18/20
10/10 [==============================] - 0s 8ms/step - loss: 7.8436 - mean_absolute_error: 1.7485 - val_loss: 9.9440 - val_mean_absolute_error: 2.0487
Epoch 19/20
10/10 [==============================] - 0s 7ms/step - loss: 7.7065 - mean_absolute_error: 1.7692 - val_loss: 9.9310 - val_mean_absolute_error: 2.0834
Epoch 20/20
10/10 [==============================] - 0s 8ms/step - loss: 7.7611 - mean_absolute_error: 1.7278 - val_loss: 10.1474 - val_mean_absolute_error: 2.0222

In [ ]:
model_bogor.compile(loss=tf.losses.MeanSquaredError(),
                optimizer=tf.optimizers.Adam(0.001),
                metrics=[tf.metrics.MeanAbsoluteError()])

history_bogor = model_bogor.fit(bogor.train, epochs=epochs,
                      validation_data=bogor.val)

Epoch 1/20
10/10 [==============================] - 1s 27ms/step - loss: 888.2677 - mean_absolute_error: 21.6876 - val_loss: 649.3809 - val_mean_absolute_error: 19.2273
Epoch 2/20
10/10 [==============================] - 0s 8ms/step - loss: 501.4988 - mean_absolute_error: 16.9078 - val_loss: 387.7672 - val_mean_absolute_error: 15.1111
Epoch 3/20
10/10 [==============================] - 0s 7ms/step - loss: 284.7609 - mean_absolute_error: 12.8963 - val_loss: 191.7494 - val_mean_absolute_error: 10.4230
Epoch 4/20
10/10 [==============================] - 0s 7ms/step - loss: 123.9475 - mean_absolute_error: 8.1518 - val_loss: 65.4369 - val_mean_absolute_error: 5.5850
Epoch 5/20
10/10 [==============================] - 0s 7ms/step - loss: 43.3524 - mean_absolute_error: 4.7880 - val_loss: 22.2902 - val_mean_absolute_error: 3.2188
Epoch 6/20
10/10 [==============================] - 0s 8ms/step - loss: 20.7900 - mean_absolute_error: 3.2709 - val_loss: 12.3921 - val_mean_absolute_error: 2.7598
Epoch 7/20
10/10 [==============================] - 0s 7ms/step - loss: 14.2239 - mean_absolute_error: 2.6675 - val_loss: 9.8736 - val_mean_absolute_error: 2.1896
Epoch 8/20
10/10 [==============================] - 0s 7ms/step - loss: 11.6785 - mean_absolute_error: 2.3130 - val_loss: 8.6687 - val_mean_absolute_error: 1.8793
Epoch 9/20
10/10 [==============================] - 0s 7ms/step - loss: 11.6528 - mean_absolute_error: 2.2956 - val_loss: 9.0429 - val_mean_absolute_error: 1.7716
Epoch 10/20
10/10 [==============================] - 0s 7ms/step - loss: 11.5082 - mean_absolute_error: 2.2411 - val_loss: 9.2665 - val_mean_absolute_error: 1.7237
Epoch 11/20
10/10 [==============================] - 0s 7ms/step - loss: 11.3942 - mean_absolute_error: 2.2230 - val_loss: 8.9748 - val_mean_absolute_error: 1.7425
Epoch 12/20
10/10 [==============================] - 0s 7ms/step - loss: 11.0811 - mean_absolute_error: 2.1798 - val_loss: 8.2349 - val_mean_absolute_error: 1.7258
Epoch 13/20
10/10 [==============================] - 0s 7ms/step - loss: 11.3402 - mean_absolute_error: 2.1928 - val_loss: 8.3408 - val_mean_absolute_error: 1.7083
Epoch 14/20
10/10 [==============================] - 0s 7ms/step - loss: 11.1667 - mean_absolute_error: 2.1646 - val_loss: 8.9744 - val_mean_absolute_error: 1.7640
Epoch 15/20
10/10 [==============================] - 0s 8ms/step - loss: 11.1716 - mean_absolute_error: 2.1753 - val_loss: 8.4096 - val_mean_absolute_error: 1.6885
Epoch 16/20
10/10 [==============================] - 0s 7ms/step - loss: 11.2569 - mean_absolute_error: 2.1806 - val_loss: 9.5230 - val_mean_absolute_error: 1.8488
Epoch 17/20
10/10 [==============================] - 0s 8ms/step - loss: 11.1655 - mean_absolute_error: 2.1704 - val_loss: 7.9373 - val_mean_absolute_error: 1.6261
Epoch 18/20
10/10 [==============================] - 0s 7ms/step - loss: 11.2071 - mean_absolute_error: 2.1741 - val_loss: 9.3402 - val_mean_absolute_error: 1.7808
Epoch 19/20
10/10 [==============================] - 0s 7ms/step - loss: 10.9481 - mean_absolute_error: 2.1521 - val_loss: 8.5889 - val_mean_absolute_error: 1.7106
Epoch 20/20
10/10 [==============================] - 0s 7ms/step - loss: 10.9094 - mean_absolute_error: 2.1485 - val_loss: 8.1439 - val_mean_absolute_error: 1.6893

In [ ]:
def forecast(subround,location,model_bandung=model_bandung,model_bogor=model_bogor) :
  output  =  []
  df_bandung_copy = df_bandung.copy()
  df_bogor_copy = df_bogor.copy()
  if location == 'Kab.Bandung'  :
    for i in range(subround):
      input = df_bandung_copy[-width:]
      input_forecast = np.array(input)[np.newaxis]
      temp = model_bandung.predict(input_forecast)
      
      temp = np.squeeze(temp, axis=None)
      output.append(temp)
      df_bandung_copy = df_bandung_copy.append(pd.DataFrame([temp], columns=['Tn','Tx','Tavg','RH_avg','RR','ss','ff_avg','ff_x','ff_y']))
      print(df_bandung_copy)
  if location == 'Kab.Bogor'  :
    for i in range(subround):
      input = df_bogor_copy[-width:]
      input_forecast = np.array(input)[np.newaxis]
      temp = model_bandung.predict(input_forecast)
      temp = np.squeeze(temp, axis=None)
      output.append(temp)
      df_bogor_copy = df_bandung_copy.append(pd.DataFrame([temp], columns=['Tn','Tx','Tavg','RH_avg','RR','ss','ff_avg','ff_x','ff_y']))
      print(df_bandung_copy)
  return output

In [ ]:
output = forecast(3,'Kab.Bandung')
print(output)

           Tn         Tx       Tavg  ...    ff_avg          ff_x          ff_y
0   20.791667  27.620833  23.312500  ...  2.416667  2.943141e-01 -4.490365e+00
1   19.750000  28.960714  23.646429  ...  1.821429 -2.611570e-01 -3.096148e+00
2   18.259259  30.370370  23.407407  ...  1.814815 -3.220859e+00  9.371743e-02
3   20.916667  27.808333  23.154167  ...  2.208333 -7.347881e-16 -4.000000e+00
4   19.321429  29.042857  23.146429  ...  1.678571 -2.870328e+00 -7.404088e-01
5   19.000000  30.808333  23.891667  ...  1.750000 -3.070184e+00  9.313300e-01
6   20.935484  28.306452  23.429032  ...  2.161290 -2.078276e+00 -3.530485e+00
7   20.392857  28.678571  23.507143  ...  1.535714 -2.540173e+00  1.596096e+00
8   19.130435  30.065217  23.782609  ...  1.695652 -3.024563e+00  3.387942e-01
9   20.285714  27.014286  23.371429  ...  1.571429  1.246411e-01  3.569253e+00
10  19.888889  29.366667  25.033333  ...  0.666667 -1.800567e+00 -2.259123e+00
11  18.750000  29.200000  23.450000  ...  1.000000  6.262790e-01 -4.456206e+00
12  20.363636  28.618182  23.263636  ...  1.090909 -1.490289e+00 -4.197858e+00
13  19.687500  29.768750  23.568750  ...  1.250000 -3.486258e+00 -7.330813e-01
14  18.750000  31.487500  23.750000  ...  1.625000 -2.772082e+00 -2.136718e+00
15  20.823529  29.317647  23.658824  ...  1.411765 -3.070011e+00 -1.857542e+00
16  21.055556  29.105556  23.861111  ...  1.111111 -2.997744e+00 -1.163261e-01
17  20.458333  29.016667  23.641667  ...  1.625000 -3.440179e+00 -1.002721e+00
18  21.136364  29.440909  24.277273  ...  2.636364 -1.597804e+00 -4.737829e+00
19  20.347826  29.760870  24.117391  ...  1.826087 -3.274030e+00  2.518178e+00
20  19.480000  30.536000  24.012000  ...  1.560000 -2.978035e+00  2.360362e+00
21  20.653846  28.123077  23.411538  ...  2.576923 -2.130990e+00 -4.734865e+00
22  19.758621  29.934483  23.793103  ...  1.413793 -3.482759e+00  4.265149e-16
23  18.925926  30.981481  23.822222  ...  2.185185 -4.223353e+00  1.384334e+00
24  20.551613  28.961290  23.680645  ...  2.322581 -8.546894e-01 -5.188135e+00
25  20.055172  29.713793  23.851724  ...  1.620690 -4.269429e+00 -8.059186e-01
26  18.241379  31.889655  23.800000  ...  2.241379 -4.774341e+00  1.233196e+00
27  21.200000  28.953846  23.865385  ...  2.000000 -1.326883e+00 -4.580933e+00
28  20.614286  29.366667  23.904762  ...  1.333333 -3.093364e+00 -1.585875e+00
29  19.883333  30.583333  24.258333  ...  2.000000 -2.335413e+00  3.550823e+00
0   19.242756  29.506313  23.840855  ...  2.636163 -2.260380e+00 -1.665497e+00

[31 rows x 9 columns]
           Tn         Tx       Tavg  ...    ff_avg          ff_x          ff_y
0   20.791667  27.620833  23.312500  ...  2.416667  2.943141e-01 -4.490365e+00
1   19.750000  28.960714  23.646429  ...  1.821429 -2.611570e-01 -3.096148e+00
2   18.259259  30.370370  23.407407  ...  1.814815 -3.220859e+00  9.371743e-02
3   20.916667  27.808333  23.154167  ...  2.208333 -7.347881e-16 -4.000000e+00
4   19.321429  29.042857  23.146429  ...  1.678571 -2.870328e+00 -7.404088e-01
5   19.000000  30.808333  23.891667  ...  1.750000 -3.070184e+00  9.313300e-01
6   20.935484  28.306452  23.429032  ...  2.161290 -2.078276e+00 -3.530485e+00
7   20.392857  28.678571  23.507143  ...  1.535714 -2.540173e+00  1.596096e+00
8   19.130435  30.065217  23.782609  ...  1.695652 -3.024563e+00  3.387942e-01
9   20.285714  27.014286  23.371429  ...  1.571429  1.246411e-01  3.569253e+00
10  19.888889  29.366667  25.033333  ...  0.666667 -1.800567e+00 -2.259123e+00
11  18.750000  29.200000  23.450000  ...  1.000000  6.262790e-01 -4.456206e+00
12  20.363636  28.618182  23.263636  ...  1.090909 -1.490289e+00 -4.197858e+00
13  19.687500  29.768750  23.568750  ...  1.250000 -3.486258e+00 -7.330813e-01
14  18.750000  31.487500  23.750000  ...  1.625000 -2.772082e+00 -2.136718e+00
15  20.823529  29.317647  23.658824  ...  1.411765 -3.070011e+00 -1.857542e+00
16  21.055556  29.105556  23.861111  ...  1.111111 -2.997744e+00 -1.163261e-01
17  20.458333  29.016667  23.641667  ...  1.625000 -3.440179e+00 -1.002721e+00
18  21.136364  29.440909  24.277273  ...  2.636364 -1.597804e+00 -4.737829e+00
19  20.347826  29.760870  24.117391  ...  1.826087 -3.274030e+00  2.518178e+00
20  19.480000  30.536000  24.012000  ...  1.560000 -2.978035e+00  2.360362e+00
21  20.653846  28.123077  23.411538  ...  2.576923 -2.130990e+00 -4.734865e+00
22  19.758621  29.934483  23.793103  ...  1.413793 -3.482759e+00  4.265149e-16
23  18.925926  30.981481  23.822222  ...  2.185185 -4.223353e+00  1.384334e+00
24  20.551613  28.961290  23.680645  ...  2.322581 -8.546894e-01 -5.188135e+00
25  20.055172  29.713793  23.851724  ...  1.620690 -4.269429e+00 -8.059186e-01
26  18.241379  31.889655  23.800000  ...  2.241379 -4.774341e+00  1.233196e+00
27  21.200000  28.953846  23.865385  ...  2.000000 -1.326883e+00 -4.580933e+00
28  20.614286  29.366667  23.904762  ...  1.333333 -3.093364e+00 -1.585875e+00
29  19.883333  30.583333  24.258333  ...  2.000000 -2.335413e+00  3.550823e+00
0   19.242756  29.506313  23.840855  ...  2.636163 -2.260380e+00 -1.665497e+00
0   20.580200  30.979143  24.702003  ...  2.248733 -2.722765e+00 -9.977937e-01

[32 rows x 9 columns]
           Tn         Tx       Tavg  ...    ff_avg          ff_x          ff_y
0   20.791667  27.620833  23.312500  ...  2.416667  2.943141e-01 -4.490365e+00
1   19.750000  28.960714  23.646429  ...  1.821429 -2.611570e-01 -3.096148e+00
2   18.259259  30.370370  23.407407  ...  1.814815 -3.220859e+00  9.371743e-02
3   20.916667  27.808333  23.154167  ...  2.208333 -7.347881e-16 -4.000000e+00
4   19.321429  29.042857  23.146429  ...  1.678571 -2.870328e+00 -7.404088e-01
5   19.000000  30.808333  23.891667  ...  1.750000 -3.070184e+00  9.313300e-01
6   20.935484  28.306452  23.429032  ...  2.161290 -2.078276e+00 -3.530485e+00
7   20.392857  28.678571  23.507143  ...  1.535714 -2.540173e+00  1.596096e+00
8   19.130435  30.065217  23.782609  ...  1.695652 -3.024563e+00  3.387942e-01
9   20.285714  27.014286  23.371429  ...  1.571429  1.246411e-01  3.569253e+00
10  19.888889  29.366667  25.033333  ...  0.666667 -1.800567e+00 -2.259123e+00
11  18.750000  29.200000  23.450000  ...  1.000000  6.262790e-01 -4.456206e+00
12  20.363636  28.618182  23.263636  ...  1.090909 -1.490289e+00 -4.197858e+00
13  19.687500  29.768750  23.568750  ...  1.250000 -3.486258e+00 -7.330813e-01
14  18.750000  31.487500  23.750000  ...  1.625000 -2.772082e+00 -2.136718e+00
15  20.823529  29.317647  23.658824  ...  1.411765 -3.070011e+00 -1.857542e+00
16  21.055556  29.105556  23.861111  ...  1.111111 -2.997744e+00 -1.163261e-01
17  20.458333  29.016667  23.641667  ...  1.625000 -3.440179e+00 -1.002721e+00
18  21.136364  29.440909  24.277273  ...  2.636364 -1.597804e+00 -4.737829e+00
19  20.347826  29.760870  24.117391  ...  1.826087 -3.274030e+00  2.518178e+00
20  19.480000  30.536000  24.012000  ...  1.560000 -2.978035e+00  2.360362e+00
21  20.653846  28.123077  23.411538  ...  2.576923 -2.130990e+00 -4.734865e+00
22  19.758621  29.934483  23.793103  ...  1.413793 -3.482759e+00  4.265149e-16
23  18.925926  30.981481  23.822222  ...  2.185185 -4.223353e+00  1.384334e+00
24  20.551613  28.961290  23.680645  ...  2.322581 -8.546894e-01 -5.188135e+00
25  20.055172  29.713793  23.851724  ...  1.620690 -4.269429e+00 -8.059186e-01
26  18.241379  31.889655  23.800000  ...  2.241379 -4.774341e+00  1.233196e+00
27  21.200000  28.953846  23.865385  ...  2.000000 -1.326883e+00 -4.580933e+00
28  20.614286  29.366667  23.904762  ...  1.333333 -3.093364e+00 -1.585875e+00
29  19.883333  30.583333  24.258333  ...  2.000000 -2.335413e+00  3.550823e+00
0   19.242756  29.506313  23.840855  ...  2.636163 -2.260380e+00 -1.665497e+00
0   20.580200  30.979143  24.702003  ...  2.248733 -2.722765e+00 -9.977937e-01
0   20.042292  29.877525  24.034101  ...  1.802033 -2.713897e+00 -9.936705e-01

[33 rows x 9 columns]
[array([19.242756 , 29.506313 , 23.840855 , 76.18334  ,  7.009796 ,
        5.542873 ,  2.636163 , -2.2603803, -1.6654973], dtype=float32), array([20.5802    , 30.979143  , 24.702003  , 78.49862   ,  6.663428  ,
        5.2127123 ,  2.2487333 , -2.722765  , -0.99779373], dtype=float32), array([20.042292 , 29.877525 , 24.034101 , 77.18723  ,  6.54934  ,
        5.205597 ,  1.8020332, -2.7138968, -0.9936705], dtype=float32)]

In [ ]:
# save dataframe
df_bandung.to_csv('./df_bandung.csv')
df_bogor.to_csv('./df_bogor.csv')

In [ ]:
# Save model
model_bandung.save('./model_bandung.h5')
model_bogor.save('./model_bogor.h5')